**Importação de Bibliotecas**

In [12]:
import pandas as pd
import numpy as np
import tensorflow as tf
import sklearn

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras import utils as np_utils
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

**Base de dados**

In [2]:
base = pd.read_csv('/content/iris.csv')
X = base.iloc[:, 0:4].values
y = base.iloc[:, 4].values

**Tratamento Base de dados y**

In [4]:
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)
y = np_utils.to_categorical(y)

X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(X, y, test_size=0.25)

**Estrutura da Rede Neural**

In [5]:
rede_neural = Sequential([
    tf.keras.layers.InputLayer(shape = (4,)),
    tf.keras.layers.Dense(units = 4, activation = 'relu'),
    tf.keras.layers.Dense(units = 4, activation = 'relu'),
    tf.keras.layers.Dense(units = 3, activation = 'softmax')
])

In [6]:
rede_neural.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['categorical_accuracy'])

**Treinamento do Modelo**

In [7]:
rede_neural.fit(X_treinamento, y_treinamento, batch_size = 10, epochs = 1000, validation_data = (X_teste, y_teste))

Epoch 1/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - categorical_accuracy: 0.3086 - loss: 1.1283
Epoch 2/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.3035 - loss: 1.1305 
Epoch 3/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.3245 - loss: 1.1129 
Epoch 4/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.1484 - loss: 1.1068 
Epoch 5/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.0672 - loss: 1.1049     
Epoch 6/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.3082 - loss: 1.1003 
Epoch 7/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.3796 - loss: 1.0956 
Epoch 8/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.3223 - loss: 1.0939 
Epoch 9/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.3831 - loss: 1.0870 
Epoch 10/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.2595 - loss: 1.0965 
Epoch 

**Avaliação do Modelo**

In [10]:
previsoes = rede_neural.predict(X_teste)
previsoes = previsoes > 0.5

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step


In [22]:
y_teste2 = [np.argmax(t) for t in y_teste]
previsoes2 = [np.argmax(t) for t in previsoes]

accuracy = accuracy_score(y_teste2, previsoes2)
c_matrix = confusion_matrix(y_teste2, previsoes2)

print(f"Acurácia do modelo: {accuracy:.2f}")
print(f"\nMatrix de Confusão:")
print(c_matrix)

Acurácia do modelo: 0.92

Matrix de Confusão:
[[15  0  0]
 [ 0  9  3]
 [ 0  0 11]]
